import express from "express";
import GetAdsLocationController from "../../controllers/departmentOfficer/get-ads-location.controller.js";
import getTheAdsRoute from "../get-data/get-the-ads.route.js";
import getReportRoutes from "../get-data/get-report.route.js";
import sendReport from "../get-data/send-report.route.js";
import getAdsPanel from "../get-data/get-ads-panel.route.js";
import getWard from "../get-data/get-ward.route.js";
import getDistrict from "../get-data/get-district.route.js";
const router = express.Router();
router.use("/get-ads-location", getTheAdsRoute);
router.use("/get-report-location", getReportRoutes);
router.use("/get-ads-panel", getAdsPanel);
router.use("/send-report", sendReport);
router.use("/get-ward", getWard);
router.use("/get-district", getDistrict);
export default router;
